baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Blog"

[params]
  homeText = "You just made a Hugo blog from scratch."
  dateFormat = "Jan 2, 2006"

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[taxonomies]
  tag = "tags"
